### ISSUE TITLE
DiscordX compatibilty issues with MacOS Sierra

### ISSUE THREAD

**Issue by sskewer** [AsadAzam/DiscordX#2]
After resolving some compatibility issues with my version of macOS Sierra, I was able to **successfully build** the application. 

However when it starts, I am **not prompted for any permissions** and it doesn't seem to work at all.

How do I grant `Automation` permissions?

**Comment by AsadAzam** [comment]
I have no way to reproduce the compatibility issues as I don't have a Mac running Sierra. Could you tell me what compatibility issues were you having. I do think that the automation scripts might have an issue or else the RPFX (Discord Rich Presence for swift) might be having some issues.

**Comment by sskewer** [comment]
As written on your GitHub repository, the program should ask me for **permissions** to allow the program to **monitor Xcode**. 

When I open the program, **nothing happens** and no permission is asked of me. Once started, the program does not give **any errors**, but it is as if it had not started.

I don't know how to proceed and what to check that everything has started correctly.

**Comment by AsadAzam** [comment]
Sorry for the late reply can you run all the apple scripts from the readme and tell me if they work?
