### ISSUE TITLE
XCode 13.2

### ISSUE THREAD

**Issue by allexks** [AsadAzam/DiscordX#3]
I guess it seems that the executable from the 1.0.3 release tag is not working with the new XCode 13?

**Comment by AsadAzam** [comment]
I just checked it is working fine on Xcode 13.1 (13A1030d).
Did you just run the app from the 1.0.3 release?
If that's the case then that's not going to work. Check issue https://github.com/AsadAzam/DiscordX/issues/1-756563378

**Comment by allexks** [comment]
> I just checked it is working fine on Xcode 13.1 (13A1030d). Did you just run the app from the 1.0.3 release? If that's the case then that's not going to work. Check issue #1

Yeah I see. I tried that as well, but it does not load the images and does not display the names of files - only the project name or just "xcode" - do you have any idea as to what the issue might be there?

**Comment by AsadAzam** [comment]
I had the same issue, as long as the window is active you will be able to see the icon once it's inactive it doesn't show the icon. I will try to look into this.

**Comment by allexks** [comment]
> I had the same issue, as long as the window is active you will be able to see the icon once it's inactive it doesn't show the icon. I will try to look into this.

Oh I see. Alright, thanks for clarifying

**Comment by AsadAzam** [comment]
Fixed in [1.0.4](https://github.com/AsadAzam/DiscordX/releases/tag/1.0.4)
