### ISSUE TITLE
Swift Tool version error

### ISSUE THREAD

**Issue by Skyline-23** [AsadAzam/DiscordX#4]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/62983047/146641456-baf3bd66-7deb-440d-8628-f336a24762c7.png">

when I run this project, this error occurred. How can I resolve this error?

**Comment by AsadAzam** [comment]
Which Xcode version are you using I was having the same issue on 13.2, turns out it was an issue with Xcode itself. [Link](https://developer.apple.com/forums/thread/696504)
