### ISSUE TITLE
GUI support?

### ISSUE THREAD

**Issue by starrywonder** [AsadAzam/DiscordX#5]
Adding GUI support for this would be nice. It would reduce the number of steps needed for closing out of the shortcut (adding `.app` into the Applications folder and having to go into the Activity Monitor)

**Comment by AsadAzam** [comment]
I have planned for a simple GUI; it will be there in the next release. I will start working on some other features in a few days. Till then, hold tight. Thanks for the support.

**Comment by AsadAzam** [comment]
The current commit [38d9a5e](https://github.com/AsadAzam/DiscordX/commit/38d9a5e12907a900cf97024785c2ff977f5aea3b) has a simple menu bar that currently has the support for starting & stopping the DiscordX app, as well as it has the option to close the app completely. The app will have some other features and a UI soon.
